// Pools tab: SF Rec & Park public swimming pools with their parsed weekly swim
// schedules (data/pools.js, generated by scripts/build-pools.js). Shows what's
// happening "now"/today at each pool, a session-type filter, the city-wide fee
// schedule, and a link to the official seasonal PDF (the source of truth).
import React, { useMemo, useState } from 'react';
import {
  Linking,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { POOLS, POOL_FEES, POOL_CLOSURES, POOL_SESSION_KINDS } from '../data/pools';
import { haversineMiles, formatDistance } from '../lib/distance';
import { openDirections } from '../lib/maps';
import { fmtClock } from '../lib/datetime';
import { useI18n } from '../lib/i18n';
import ScrollTopFab, { useScrollTop } from './ScrollTopFab';

const DOW_KEYS = ['day.0', 'day.1', 'day.2', 'day.3', 'day.4', 'day.5', 'day.6'];
// Color palette per session kind (pill background / text).
const KIND_TONE = {
  lap: { bg: '#e3effb', fg: '#1f5fa8' },
  family: { bg: '#e7f5ec', fg: '#1f8a4c' },
  senior: { bg: '#f3ecfb', fg: '#6b3fa0' },
  lessons: { bg: '#fdf2e0', fg: '#b56a14' },
  adult_lessons: { bg: '#fdf2e0', fg: '#b56a14' },
  parent_child: { bg: '#fde9f1', fg: '#b03a73' },
  exercise: { bg: '#e0f5f3', fg: '#1f8a86' },
  camp: { bg: '#eef1f4', fg: '#5b6b7b' },
  rental: { bg: '#eef1f4', fg: '#5b6b7b' },
  other: { bg: '#eef1f4', fg: '#5b6b7b' },
};
const tone = (k) => KIND_TONE[k] || KIND_TONE.other;
const fmtMin = (m) => fmtClock(Math.floor(m / 60), m % 60);
const todayStr = () => {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};

export default function PoolsScreen({ userLocation }) {
  const { t } = useI18n();
  const insets = useSafeAreaInsets();
  const { scrollRef, onScroll, showTop, scrollToTop } = useScrollTop(40);
  const [query, setQuery] = useState('');
  const [kind, setKind] = useState(null); // session-type filter
  const [feesOpen, setFeesOpen] = useState(false);
  const [expanded, setExpanded] = useState(null); // pool id with full week shown

  const now = new Date();
  const dow = now.getDay();
  const nowMin = now.getHours() * 60 + now.getMinutes();
  const closure = POOL_CLOSURES.find((c) => c.date === todayStr());

  const distOf = (p) =>
    userLocation && p.lat != null ? haversineMiles(userLocation.lat, userLocation.lng, p.lat, p.lng) : null;

  // Decorate each pool with today's sessions + open-now / next-up state.
  const list = useMemo(() => {
    const q = query.trim().toLowerCase();
    return POOLS.map((p) => {
      const today = (p.sessions[dow] || []).filter((s) => !kind || s.kind === kind);
      const openNow = !closure && today.find((s) => nowMin >= s.start && nowMin < s.end);
      const next = !closure && today.find((s) => s.start > nowMin);
      const d = distOf(p);
      return { ...p, today, openNow, next, dist: d };
    })
      .filter((p) => {
        if (q && !p.name.toLowerCase().includes(q)) return false;
        if (kind && !p.programs.includes(kind)) return false;
        return true;
      })
      .sort((a, b) => {
        if (a.dist != null && b.dist != null) return a.dist - b.dist;
        return a.name.localeCompare(b.name);
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query, kind, userLocation, dow, nowMin, closure]);

  return (
    <View style={[styles.page, { paddingTop: insets.top + 14 }]}>
      <Text style={styles.title}>{t('pools.title')}</Text>
      <Text style={styles.sub}>{t('pools.sub')}</Text>

      <View style={styles.search}>
        <Ionicons name="search" size={16} color="#8a99a8" />
        <TextInput
          style={styles.searchInput}
          placeholder={t('pools.searchPh')}
          placeholderTextColor="#9aa7b4"
          value={query}
          onChangeText={setQuery}
          returnKeyType="search"
          clearButtonMode="while-editing"
          autoCorrect={false}
        />
        <Pressable style={styles.feesBtn} onPress={() => setFeesOpen(true)} hitSlop={6}>
          <Ionicons name="pricetag-outline" size={14} color="#2f74d6" />
          <Text style={styles.feesBtnText}>{t('pools.fees')}</Text>
        </Pressable>
      </View>

      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.kindRow}
        contentContainerStyle={styles.kindRowInner}
      >
        {[null, ...POOL_SESSION_KINDS].map((k) => {
          const active = kind === k;
          return (
            <Pressable
              key={k || 'all'}
              onPress={() => setKind(k)}
              style={[styles.kindChip, active && styles.kindChipActive]}
            >
              <Text style={[styles.kindChipText, active && styles.kindChipTextActive]}>
                {k ? t('pool.kind.' + k) : t('pools.allKinds')}
              </Text>
            </Pressable>
          );
        })}
      </ScrollView>

      <ScrollView
        ref={scrollRef}
        onScroll={onScroll}
        scrollEventThrottle={16}
        style={{ flex: 1 }}
        contentContainerStyle={{ paddingBottom: 28 }}
        showsVerticalScrollIndicator={false}
      >
        {closure && <Text style={styles.closure}>{t('pools.closedToday', { holiday: closure.label })}</Text>}

        {list.map((p) => {
          const isOpen = !!p.openNow;
          const showWeek = expanded === p.id;
          return (
            <View key={p.id} style={styles.card}>
              <View style={styles.cardTop}>
                <Text style={styles.cardName}>🏊 {p.name}</Text>
                {p.dist != null && <Text style={styles.dist}>{formatDistance(p.dist)}</Text>}
              </View>

              <View style={styles.statusRow}>
                {isOpen ? (
                  <View style={[styles.statusPill, styles.openPill]}>
                    <View style={styles.openDot} />
                    <Text style={styles.openText}>
                      {t('pool.openNow', { kind: t('pool.kind.' + p.openNow.kind), end: fmtMin(p.openNow.end) })}
                    </Text>
                  </View>
                ) : p.next ? (
                  <View style={[styles.statusPill, styles.nextPill]}>
                    <Text style={styles.nextText}>
                      {t('pool.next', { kind: t('pool.kind.' + p.next.kind), at: fmtMin(p.next.start) })}
                    </Text>
                  </View>
                ) : (
                  <View style={[styles.statusPill, styles.closedPill]}>
                    <Text style={styles.closedText}>
                      {p.today.length ? t('pool.doneForDay') : t('pool.closedDay')}
                    </Text>
                  </View>
                )}
                <Text style={styles.season}>{p.season}</Text>
              </View>

              {/* Today's sessions */}
              {p.today.length > 0 && (
                <>
                  <Text style={styles.dayLabel}>{t('pool.today')}</Text>
                  <View style={styles.sessRow}>
                    {p.today.map((s, i) => (
                      <View key={i} style={[styles.sess, { backgroundColor: tone(s.kind).bg }]}>
                        <Text style={[styles.sessKind, { color: tone(s.kind).fg }]}>{t('pool.kind.' + s.kind)}</Text>
                        <Text style={[styles.sessTime, { color: tone(s.kind).fg }]}>
                          {fmtMin(s.start)}–{fmtMin(s.end)}
                        </Text>
                      </View>
                    ))}
                  </View>
                </>
              )}

              {/* Full week (expandable) */}
              {showWeek &&
                p.sessions.map((day, i) =>
                  day.length ? (
                    <View key={i} style={styles.weekDay}>
                      <Text style={styles.weekDow}>{t(DOW_KEYS[i])}</Text>
                      <View style={styles.sessRow}>
                        {day
                          .filter((s) => !kind || s.kind === kind)
                          .map((s, j) => (
                            <View key={j} style={[styles.sess, { backgroundColor: tone(s.kind).bg }]}>
                              <Text style={[styles.sessKind, { color: tone(s.kind).fg }]}>{t('pool.kind.' + s.kind)}</Text>
                              <Text style={[styles.sessTime, { color: tone(s.kind).fg }]}>
                                {fmtMin(s.start)}–{fmtMin(s.end)}
                              </Text>
                            </View>
                          ))}
                      </View>
                    </View>
                  ) : null
                )}

              {!!p.note && <Text style={styles.note}>{p.note}</Text>}

              <View style={styles.actions}>
                <Pressable style={styles.actBtn} onPress={() => setExpanded(showWeek ? null : p.id)}>
                  <Ionicons name={showWeek ? 'chevron-up' : 'calendar-outline'} size={13} color="#2f74d6" />
                  <Text style={styles.actText}>{showWeek ? t('pool.hideWeek') : t('pool.fullWeek')}</Text>
                </Pressable>
                {p.lat != null && (
                  <Pressable style={styles.actBtn} onPress={() => openDirections(p.lat, p.lng, p.name)}>
                    <Ionicons name="navigate" size={13} color="#2f74d6" />
                    <Text style={styles.actText}>{t('directions')}</Text>
                  </Pressable>
                )}
                {!!p.phone && (
                  <Pressable style={styles.actBtn} onPress={() => Linking.openURL('tel:' + p.phone.replace(/[^\d]/g, ''))}>
                    <Ionicons name="call-outline" size={13} color="#2f74d6" />
                    <Text style={styles.actText}>{p.phone}</Text>
                  </Pressable>
                )}
              </View>

              <View style={styles.pdfRow}>
                {p.scheduleUrls.map((u, i) => (
                  <Pressable key={i} style={styles.pdfBtn} onPress={() => Linking.openURL(u.url)}>
                    <Ionicons name="document-text-outline" size={12} color="#46586a" />
                    <Text style={styles.pdfText}>
                      {p.scheduleUrls.length > 1 && /warm/i.test(u.label)
                        ? t('pool.pdfWarm')
                        : p.scheduleUrls.length > 1 && /cool/i.test(u.label)
                        ? t('pool.pdfCool')
                        : t('pool.pdf')}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </View>
          );
        })}

        {list.length === 0 && <Text style={styles.empty}>{t('pools.empty')}</Text>}
        <Text style={styles.disclaimer}>{t('pools.disclaimer')}</Text>
      </ScrollView>

      <ScrollTopFab show={showTop} onPress={scrollToTop} bottom={insets.bottom + 92} />

      {/* Fees sheet */}
      <Modal visible={feesOpen} transparent animationType="slide" onRequestClose={() => setFeesOpen(false)}>
        <Pressable style={styles.backdrop} onPress={() => setFeesOpen(false)}>
          <Pressable style={[styles.sheet, { paddingBottom: insets.bottom + 16 }]} onPress={() => {}}>
            <View style={styles.sheetHandle} />
            <Text style={styles.sheetTitle}>{t('pools.feesTitle')}</Text>
            <Text style={styles.feesEffective}>{t('pools.feesEffective', { date: POOL_FEES.effective })}</Text>
            <ScrollView style={{ maxHeight: 420 }} showsVerticalScrollIndicator={false}>
              {POOL_FEES.groups.map((g) => (
                <View key={g.id} style={styles.feeGroup}>
                  <View style={styles.feeGroupHead}>
                    <Text style={styles.feeGroupLabel}>{g.label}</Text>
                    <Text style={styles.feeDropIn}>{t('pools.dropInPrice', { price: g.dropIn })}</Text>
                  </View>
                  {g.passes.map(([label, price], i) => (
                    <View key={i} style={styles.feeRow}>
                      <Text style={styles.feeLabel}>{label}</Text>
                      <Text style={styles.feePrice}>${price}</Text>
                    </View>
                  ))}
                </View>
              ))}
            </ScrollView>
            <Pressable style={styles.pdfBtn} onPress={() => Linking.openURL(POOL_FEES.source)}>
              <Ionicons name="document-text-outline" size={12} color="#46586a" />
              <Text style={styles.pdfText}>{t('pools.feesSource')}</Text>
            </Pressable>
          </Pressable>
        </Pressable>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#eef1f5', paddingHorizontal: 16 },
  title: { fontSize: 24, fontWeight: '800', color: '#0d1b2a' },
  sub: { fontSize: 13, color: '#6b7a8a', marginTop: 2, marginBottom: 10 },

  search: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 42,
    gap: 8,
    borderWidth: 1,
    borderColor: '#e6e9ee',
  },
  searchInput: { flex: 1, fontSize: 15, color: '#0d1b2a' },
  feesBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  feesBtnText: { color: '#2f74d6', fontWeight: '700', fontSize: 13 },

  kindRow: { marginTop: 10, marginBottom: 2, flexGrow: 0 },
  kindRowInner: { gap: 8, paddingRight: 16 },
  kindChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e6e9ee' },
  kindChipActive: { backgroundColor: '#2f74d6', borderColor: '#2f74d6' },
  kindChipText: { color: '#46586a', fontWeight: '700', fontSize: 13 },
  kindChipTextActive: { color: '#fff' },

  closure: { backgroundColor: '#fdeaea', color: '#c23b3b', fontWeight: '700', fontSize: 13, padding: 10, borderRadius: 10, marginTop: 12, overflow: 'hidden' },

  card: { backgroundColor: '#fff', borderRadius: 14, padding: 14, marginTop: 12, borderWidth: 1, borderColor: '#e9edf1' },
  cardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardName: { fontSize: 16, fontWeight: '800', color: '#0d1b2a', flex: 1 },
  dist: { fontSize: 12, color: '#6b7a8a', fontWeight: '600', marginLeft: 8 },

  statusRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 8 },
  statusPill: { flexDirection: 'row', alignItems: 'center', borderRadius: 14, paddingHorizontal: 10, paddingVertical: 5, gap: 5 },
  openPill: { backgroundColor: '#e7f5ec' },
  openDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#1f9d55' },
  openText: { color: '#1f8a4c', fontWeight: '800', fontSize: 12 },
  nextPill: { backgroundColor: '#e3effb' },
  nextText: { color: '#1f5fa8', fontWeight: '700', fontSize: 12 },
  closedPill: { backgroundColor: '#eef1f4' },
  closedText: { color: '#6b7a8a', fontWeight: '700', fontSize: 12 },
  season: { marginLeft: 'auto', fontSize: 11, color: '#9aa7b4', fontWeight: '600' },

  dayLabel: { fontSize: 11, fontWeight: '800', color: '#8a99a8', textTransform: 'uppercase', letterSpacing: 0.5, marginTop: 12, marginBottom: 6 },
  sessRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  sess: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 },
  sessKind: { fontSize: 12, fontWeight: '800' },
  sessTime: { fontSize: 11, fontWeight: '600', marginTop: 1 },

  weekDay: { marginTop: 10 },
  weekDow: { fontSize: 12, fontWeight: '800', color: '#0d1b2a', marginBottom: 5 },

  note: { fontSize: 12, color: '#6b7a8a', marginTop: 10, fontStyle: 'italic' },

  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginTop: 12 },
  actBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  actText: { color: '#2f74d6', fontWeight: '700', fontSize: 12 },

  pdfRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  pdfBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#f1f4f7', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 6, marginTop: 8 },
  pdfText: { color: '#46586a', fontWeight: '700', fontSize: 12 },

  empty: { textAlign: 'center', color: '#8a99a8', marginTop: 30, fontSize: 14 },
  disclaimer: { fontSize: 11, color: '#9aa7b4', textAlign: 'center', marginTop: 18, lineHeight: 16 },

  backdrop: { flex: 1, backgroundColor: 'rgba(13,27,42,0.5)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 18, borderTopRightRadius: 18, padding: 18 },
  sheetHandle: { alignSelf: 'center', width: 40, height: 4, borderRadius: 2, backgroundColor: '#d7dde3', marginBottom: 12 },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: '#0d1b2a' },
  feesEffective: { fontSize: 12, color: '#6b7a8a', marginTop: 2, marginBottom: 10 },
  feeGroup: { marginTop: 10, borderTopWidth: 1, borderTopColor: '#eef1f4', paddingTop: 10 },
  feeGroupHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  feeGroupLabel: { fontSize: 14, fontWeight: '800', color: '#0d1b2a' },
  feeDropIn: { fontSize: 13, fontWeight: '800', color: '#1f8a4c' },
  feeRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  feeLabel: { fontSize: 13, color: '#46586a' },
  feePrice: { fontSize: 13, fontWeight: '700', color: '#0d1b2a' },
});
